# Generated by Django 3.0.14 on 2026-06-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='traffic_prediction_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRAFFIC_DATE', models.CharField(max_length=30000)),
                ('TRAFFIC_TIME', models.CharField(max_length=30000)),
                ('BOROUGH', models.CharField(max_length=30000)),
                ('ZIP_CODE', models.CharField(max_length=30000)),
                ('LATITUDE', models.CharField(max_length=30000)),
                ('LONGITUDE', models.CharField(max_length=30000)),
                ('LOCATION', models.CharField(max_length=30000)),
                ('ON_STREET_NAME', models.CharField(max_length=30000)),
                ('CROSS_STREET_NAME', models.CharField(max_length=30000)),
                ('OFF_STREET_NAME', models.CharField(max_length=30000)),
                ('CONTRIBUTING_FACTOR_VEHICLE', models.CharField(max_length=30000)),
                ('REFERENCE_ID', models.CharField(max_length=30000)),
                ('TRAFFIC_VEHICLE_TYPE_CODE1', models.CharField(max_length=30000)),
                ('TRAFFIC_VEHICLE_TYPE_CODE2', models.CharField(max_length=30000)),
                ('Junction', models.CharField(max_length=30000)),
                ('Prediction', models.CharField(max_length=30000)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
